.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo8 - Debug ]----------"
	@cd "ejemplo8" && "$(MAKE)" -f  "ejemplo8.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo8 - Debug ]----------"
	@cd "ejemplo8" && "$(MAKE)" -f  "ejemplo8.mk" clean
